Add docker-compose for developing
hulthe/LaggIT pull request #25
Opened 2019-10-03 20:21 UTC by HerrNaN

Resolves #18

2019-10-03 21:12 UTC, HerrNaN commented
Seems to have a problem when getting http://localhost:8080/pkg/package.js on some machines...

2019-10-13 13:17 UTC, hulthe commented on frontend/Dockerfile
> +# RUN rustup update
Remove these comments

2019-10-13 13:21 UTC, hulthe commented on frontend/dev.nginx.conf
> +        error_page  500 502 503 504  /50x.html;
I think we should be able to remove this stuff since microserver has SPA support

2019-10-13 13:29 UTC, hulthe commented on docker-compose.yml
> +      - '8000:8000'
We don't need to expose the ports of the individual services, they are accessed through the router.

2019-10-13 13:30 UTC, hulthe requested changes
Some small cleanup left to do. And we still need to test this.

2019-11-05 12:11 UTC, hulthe commented
It works! At least on my machine...

The only problem with this is that it produces build artifacts that are owned by `root`...
I think it would be best to have the docker container inherit the UID & GID of the user.

2019-11-05 12:20 UTC, hulthe commented
Another solution might be to mount `target` in its own anonymous volume, hm...

2021-02-17 16:52 UTC, hulthe commented
Closing due to staleness

2021-02-17 16:52 UTC, closed without merging